### ISSUE TITLE
Release v9.1.7 contains a module bug

### ISSUE THREAD

**Issue by kai-dorschner-twinsity** [reactstrap/reactstrap#2726]
- components: `build`
- reactstrap version `#9.1.7`
- import method `"esm/index.js"`
- react version `#18.2.0`
- bootstrap version `#5.2.3`

### What is happening?

After upgrading the parcel bundler cannot find the folder `esm/` which is reference in the package.json like so `"module": "esm/index.js",`

### Error message in console

```
Server running at http://localhost:8080
🚨 Build failed.

@parcel/core: Failed to resolve 'reactstrap' from './src/apps/project/pages/NotFound.tsx'

  C:\Users\User\project\src\apps\currentApp\pages\NotFound.tsx:4:24
    3 | import { Link } from 'react-router-dom';
  > 4 | import { Button } from 'reactstrap';
  >   |                        ^^^^^^^^^^^^

@parcel/resolver-default: Could not load './esm/index.js' from module 'reactstrap' found in package.json#module

  C:\Users\User\project\node_modules\reactstrap\package.json:7:13
    6 |   "main": "lib/index.js",
  > 7 |   "module": "esm/index.js",
  >   |             ^^^^^^^^^^^^^^ './esm/index.js' does not exist, did you mean './lib/index.js'?'
    8 |   "types": "types/index.d.ts",
    9 |   "sideEffects": false,

```

**Comment by donyvarkeywmp** [comment]
I'm also facing this error.
`export 'Row' (imported as 'Row') was not found in 'reactstrap' (module has no exports)`

**Comment by tatasaikumar** [comment]
Getting this issue in 9.1.7 version,

export 'Modal' (imported as 'Modal') was not found in 'reactstrap' (module has no exports)
export 'ModalHeader' (imported as 'ModalHeader') was not found in 'reactstrap' (module has no exports)
export 'ModalBody' (imported as 'ModalBody') was not found in 'reactstrap' (module has no exports)
export 'ModalFooter' (imported as 'ModalFooter') was not found in 'reactstrap' (module has no exports)

**Comment by donyvarkeywmp** [comment]
> Getting this issue in 9.1.7 version,
> 
> export 'Modal' (imported as 'Modal') was not found in 'reactstrap' (module has no exports) export 'ModalHeader' (imported as 'ModalHeader') was not found in 'reactstrap' (module has no exports) export 'ModalBody' (imported as 'ModalBody') was not found in 'reactstrap' (module has no exports) export 'ModalFooter' (imported as 'ModalFooter') was not found in 'reactstrap' (module has no exports)

Fallback to version `9.1.6`

**Comment by kai-dorschner-twinsity** [comment]
The issue is probably easily fixed by the developers by just calling `npm run build:esm`, which they might have forgotten on this release.

**Comment by jitendra-yachtsman** [comment]
When i upgrade to latest version start getting following error while creating build

`Module not found: Error: Can't resolve './Container' in 'project_source/node_modules/reactstrap/lib'`

Then after try to downgrade to v9.1.6 but start facing same issue, then i also try to downgrade up to v9.1.0 but still facing same issue. I have completely remove `node_modules` and `package-lock.json` file and tried but not working at all.  i am using below vrsions.
react 18.2.0
react-dom 18.2.0
bootstrap 5.2.3
node 16.14.0

**Comment by jitendra-yachtsman** [comment]
For temporary fix i have removed `"reactstrap": "^9.1.6",` and set `"reactstrap": "9.1.6",` in package.json file and its working fine for me.

**Comment by kai-dorschner-twinsity** [comment]
Closing when https://github.com/reactstrap/reactstrap/pull/2725 is done

**Comment by illiteratewriter** [comment]
@kai-dorschner-twinsity thank you for the detailed bug report. Made fixing it easier. :)
