### ISSUE TITLE
InputGroupAddon Broken

### ISSUE THREAD

**Issue by HamadaBrest** [reactstrap/reactstrap#766]
### Issue description

- components: `InputGroupAddon`
- reactstrap version `5.0.0-alpha.3`
- bootstrap version `4.0.0-beta.2`

### What is happening?

**InputGroupAddon** Are broken even in your website

**Comment by TheSharpieOne** [comment]
They are working, but the docs are currently in flux. When a PR is merged to master, the docs automatically build. Since #758 has been merge, the docs are using bootstrap version 4.0.0-beta.3 which changed the way InputGroupAddons work. There is a PR (#762) which fixes the lib and the docs. I just merged the PR so the docs should reflex the fix soon, but the code will need to be released in order for you to use it.
For now, just clone the version you are using and run the docs locally.
#195 would help with the confusion.

**Comment by kellymears** [comment]
I was having the same problem before finding this helpful Issue.

I'm really early on in development of my project, so I updated Bootstrap to version 4.0.0-beta.3 and reactstrap to 5.0.0-alpha.4 but I'm still seeing style issues with InputGroupAddon's addonType="prepend". If I code it normally as described in the Bootstrap docs with icky old-fashioned div elements the behavior is as expected. 

I make a lot of errors nearly every day so who knows if I'm just doing something dumb, but I figured I'd flag it in the unlikely event it isn't something on my end. Everything else I've tried works perfectly. Thank you.

**Comment by mikdatdogru** [comment]
#759

**Comment by xuv** [comment]
I still have this issue with:

- reactstrap version 5.0.0-alpha.4
- bootstrap version 4.0.0-beta.3

using `<InputGroupAddon addonType="prepend">$</InputGroupAddon>` for example, shows this is the console:
`
Warning: React does not recognize the `addonType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `addontype` instead. If you accidentally passed it from a parent component, remove it from the DOM element. 
`

**Comment by supergibbs** [comment]
`reactstrap 5.0.0-alpha.4` is pretty old and is best compatible with bootstrap 4.0-beta. The master branch has quite a few commits to get it working with beta.2 and beta.3 but those aren't released yet. 

Personally I use `BS 4.0-beta.2` with `reactstrap 5.0.0-alpha.4` and manually fix the few things that break for me. All depends on what components you use. Check http://getbootstrap.com/docs/4.0/migration/ for beta.2/3 breaking changes.

**Comment by xuv** [comment]
@supergibbs: ok, thx for the tips.

**Comment by kirkins** [comment]
Having a similar issue with `<InputGroupAddon addonType="append">` not rendering as expected.

Anyone know how I can update to the fixed version? I tried `npm update reactstrap` but the version didn't change.

![react](https://user-images.githubusercontent.com/9503662/35578271-917d0a6e-05b1-11e8-99e3-ae9738b615a7.png)
